TEMPLATE = app
CONFIG += qt console
QT += core widgets
QT += sql gui
INCLUDEPATH += core database view
SOURCES += main.cpp core/Site.cpp core/Format.cpp database/Database.cpp 
SOURCES += core/State.cpp core/Scale.cpp core/User.cpp core/Status.cpp core/Usertype.cpp core/Session.cpp view/SiteView.cpp core/Geodata_record.cpp
HEADERS += core/Site.h database/Database.h core/Format.h core/State.h 
HEADERS += core/Scale.h core/User.h core/Status.h core/Usertype.h core/Session.h core/Geodata_record.h view/SiteView.h
FORMS += view/SiteView.ui